create table  RA_TEST_FOR_XCM_TB
(
REC_ID	INTEGER,            
CITY	VARCHAR2(16),
BUSI_TYPE	VARCHAR2(16),
KPI	VARCHAR2(16),
BILL_TYPE	VARCHAR2(16),
TIME_POINT	DATE,
PERIOD	INTEGER
);
ALTER TABLE RA_TEST_FOR_XCM_TB
ADD CONSTRAINT RA_TEST_FOR_XCM_TB_PK  PRIMARY KEY (REC_ID);

