
--用户表
drop table RA_SUBSCRIBER_ST_201211;
create table RA_SUBSCRIBER_ST_201211
(
SUBSID  NUMBER(14)             ,
ACCTID  NUMBER(14)             ,
SERVNUMBER  VARCHAR2(20)       ,
BRAND   VARCHAR2(16)           ,
ACTIVE  NUMBER(1)              ,
STATUS  VARCHAR2(16)
);

ALTER TABLE RA_SUBSCRIBER_ST_201211
ADD CONSTRAINT PK_RA_SUBSCRIBER_ST201211   PRIMARY KEY (SUBSID); 



--BOSS_全球通
drop table RA_IB_WL_EBXLOG_GZ_201211;
create table RA_IB_WL_EBXLOG_GZ_201211
(
LOGID   NUMBER(14)              ,
EBOXID  NUMBER(14)              ,
EBOXUNITID  NUMBER(14)          ,
EBOXUNITDETID   NUMBER(14)      ,
BEFORECHGAMT    NUMBER(16,2)    ,
AFTERCHGAMT NUMBER(16,2)        ,
OPERCODE    VARCHAR2(15)        ,
REASON  VARCHAR2(64)            ,
REASON2 VARCHAR2(64)            ,
CHGTIME DATE                    ,
SOURCE  VARCHAR2(255)           ,
YXPLANID    NUMBER(14)          ,
BI_INOUTFLAG    VARCHAR2(32)    ,
BI_CHGFLAG  NUMBER(16,2)
);

ALTER TABLE RA_IB_WL_EBXLOG_GZ_201211
ADD CONSTRAINT PK_RA_IB_WL_EBXLOG_GZ_201211   PRIMARY KEY (LOGID);

--BOSS_实销
drop table RA_RB_WL_EBXLOG_ST_201211;
create table RA_RB_WL_EBXLOG_ST_201211
(
LOGID   NUMBER(14)            ,
SUBSID  NUMBER(14)            ,
BALTYPE NUMBER(2)             ,
CHGAMT  NUMBER(14,2)          ,
AFTERCHGAMT NUMBER(14,2)      ,
OPERCODE    VARCHAR2(15)      ,
REASON  VARCHAR2(64)          ,
REASON2 VARCHAR2(64)          ,
CHGTIME DATE                  ,
YXPLANID    NUMBER(14)        ,
BASEAMT NUMBER(14,2)          ,
PRESENTAMT  NUMBER(14,2)      ,
INVALIDAMT  NUMBER(14,2)      ,
BILLFLAG    NUMBER(2)         ,
MEMO    VARCHAR2(64)          ,
LOGTYPE     NUMBER(2) 
);

ALTER TABLE RA_RB_WL_EBXLOG_ST_201211
ADD CONSTRAINT PK_RA_RB_WL_EBXLOG_ST_201211   PRIMARY KEY (LOGID);


--BOSS_OCE 
drop table RA_IB_DG_EBXLOG_SZ_201211;
create table RA_IB_DG_EBXLOG_SZ_201211
(
LOGID   NUMBER(14)             ,
EBOXID  NUMBER(14)             ,
EBOXUNITID  NUMBER(14)         ,
EBOXUNITDETID   NUMBER(14)     ,
CHGAMT  NUMBER(16,2)           ,
AFTERCHGAMT NUMBER(16,2)       ,
OPERCODE    VARCHAR2(15)       ,
REASON  VARCHAR2(64)           ,
REASON2 VARCHAR2(64)           ,
CHGTIME DATE                   ,
YXPLANID    NUMBER(14)         ,
GENBILLCYC  NUMBER(8)          ,
BASEAMT NUMBER(16,2)           ,
PRESENTAMT  NUMBER(16,2)       ,
INVALIDAMT  NUMBER(16,2)       ,
BILLFLAG    NUMBER(2)          ,
MEMO    VARCHAR2(64)
);

ALTER TABLE RA_IB_DG_EBXLOG_SZ_201211
ADD CONSTRAINT PK_RA_IB_DG_EBXLOG_SZ_201211   PRIMARY KEY (LOGID);

--NGBOSS_后付费     
drop table RA_NG_WL_EBXLOG_FS_201211; 
create table RA_NG_WL_EBXLOG_FS_201211
(
LOGID   NUMBER(20)            ,
EBOXID  NUMBER(14)            ,
EBOXUNITID  NUMBER(14)        ,
EBOXUNITDETID   NUMBER(14)    ,
BEFORECHGAMT    NUMBER(16,2)  ,
AFTERCHGAMT NUMBER(16,2)      ,
OPERCODE    VARCHAR2(15)      ,
REASON  VARCHAR2(64)          ,
CHGTIME DATE                  ,
SOURCE  VARCHAR2(255)         ,
PRODID  VARCHAR2(32)          ,
REASON2 VARCHAR2(64)
);

ALTER TABLE RA_NG_WL_EBXLOG_FS_201211
ADD CONSTRAINT PK_RA_NG_WL_EBXLOG_FS_201211   PRIMARY KEY (LOGID);


--NGBOSS_预付费
drop table RA_NG_PP_CRGLOG_ZS_201211;      
create table RA_NG_PP_CRGLOG_ZS_201211
(
EBOXID  NUMBER(14)         ,
GENDATE NUMBER(14)         ,
EBOXUNITID  NUMBER(14)     ,
SUBSID  NUMBER(14)         ,
VALIDBILLCYC    NUMBER(8)  ,
ACCTID  NUMBER(14)         ,
AMT NUMBER(14)
);

ALTER TABLE RA_NG_PP_CRGLOG_ZS_201211
ADD CONSTRAINT PK_RA_NG_PP_CRGLOG_ZS_201211   PRIMARY KEY (EBOXID,GENDATE,EBOXUNITID,SUBSID,VALIDBILLCYC,ACCTID);

--NGBOSS_集团
drop table RA_NGJT_WL_EBXLOG_FS_201211;
create table RA_NGJT_WL_EBXLOG_FS_201211
(
LOGID   NUMBER(20)            ,
EBOXID  NUMBER(14)            ,
EBOXUNITID  NUMBER(14)        ,
EBOXUNITDETID   NUMBER(14)    ,
BEFORECHGAMT    NUMBER(16,2)  ,
AFTERCHGAMT NUMBER(16,2)      ,
OPERCODE    VARCHAR2(15)      ,
REASON  VARCHAR2(64)          ,
CHGTIME DATE                  ,
SOURCE  VARCHAR2(255)         ,
PRODID  VARCHAR2(32)          ,
REASON2 VARCHAR2(64)
);

ALTER TABLE RA_NGJT_WL_EBXLOG_FS_201211
ADD CONSTRAINT PK_RA_NGJT_EBXLOG_FS_201211   PRIMARY KEY (LOGID);

  select to_char(LOGID),to_char(EBOXID),to_char(EBOXUNITID),to_char(EBOXUNITDETID),BEFORECHGAMT,AFTERCHGAMT,OPERCODE,REASON,REASON2,to_char(CHGTIME,'YYYY-MM-DD HH:Mi:ss'),SOURCE,to_char(YXPLANID),BI_CHGFLAG from  ra_ib_wl_ebxlog_st_201305 where rownum < 10
